import React, { useEffect, useState } from 'react';
import axios from 'axios';
import type { NextPage } from 'next';
import type { Products } from '../shared/interface';
import Head from 'next/head';
import { Header, SalesStats } from '../components';

const StatsPage: NextPage<Products> = ({ products }) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header />
      <div className='container d-flex justify-content-around align-items-center align-middle '>
        <SalesStats title='Top 5 Products' />
        <SalesStats title='Top 5 Unique Products' />
        <SalesStats title='Last 5 Days Sales' />
      </div>
    </>
  );
};
// client side data fetching

export default StatsPage;
